### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by haypo**
* Replace dict.iteritems() with six.iteritems(dict)
* Replace dict.itervalues() with six.itervalues(dict)
* Fix syntax of relative imports
* Get range from six.moves to get xrange() on Python 2 and range() on
  Python 3
* Replace it.next() with next(it)
* Sort also imports

### CODE REVIEW

**Comment by haypo** [comment]
Sorry, I don't know how to test my changes :-( How do I run tests?

**Comment by agrover** [comment]
Thanks haypo. So this would give us py2 and py3 compatibility without needing to run 2to3 (usually in a packaging script) every time. @thomasgoirand would this make life easier for you? @cvubrugier, thoughts?

I guess I'm ok with it...packagers could ditch the 2to3 for python3 pkgs but would pick up a runtime dependency on the "six" library -- but will give it a day or 2 to see if anyone else chimes in.

**Comment by agrover** [comment]
Our testing tramework is nonexistent. Partly because we depend on the kernel and the presence of certain hardware to test all the per-fabric bits, and partly because it hasn't been made the priority it should be, even though avoidable regressions have occurred in the past . Sigh.

**Comment by cvubrugier** [comment]
Interesting, I was thinking about using the six module to have a common code base for both Python 2 and Python 3 and not transforming the code for Python 3 with `2to3`. It's great to see @haypo tackling this problem.
As for testing, I will give @haypo's patch a try by doing some manual basic testing of targetcli with both Python 2 and Python 3.

@haypo, do you plan to perform the same change in configshell-fb and targetcli-fb? Even if eNovance probably relies on rtslib-fb only, it would be a nice addition.

**Comment by cvubrugier** [comment]
I tested targetcli-fb with @haypo's rtslib-fb changes and it works fine with both Python 2.7.9 and Python 3.4.2.

@haypo, I think you should remove `use_2to3 = True` from `setup.py` (I performed my tests without this line). Thanks!

**Comment by haypo** [comment]
> Thanks haypo. So this would give us py2 and py3 compatibility without needing to run 2to3 (usually in a packaging script) every time.

Oh. I didn't notice that setup.py uses 2to3. Maybe rtslib-fb already works fine on Python 3.

2to3 is slow and it's harder to package it if the source code is different in Python 3. For example, with wheel packages, it's better to have a single wheel package for Python 2 and Python 3.

 > Our testing tramework is nonexistent. Partly because we depend on the kernel and the presence of certain hardware to test all the per-fabric bits, (...)

You should take a look at unittest.mock (mock for Python 2) which allows to mock all system calls, or more generally mock any function call.

> @haypo, I think you should remove use_2to3 = True from setup.py (I performed my tests without this line). Thanks!

Right, I updated my patch to fix setup.py.

By running 2to3, I found a bug in _Backstore constructor: I fixed it by building a set from bs_cache.values() just to find a free index in the backstore cache. On Python 3, dict.values() is now an iterator, not a list.

I also added the Python 3 classifier to setup.py to announce that rtslib-fb is now compatible with Python 3.

> @haypo, do you plan to perform the same change in configshell-fb and targetcli-fb? Even if eNovance probably relies on rtslib-fb only, it would be a nice addition.

I ported rtslib-fb to be able to port Ceilometer to Python 3, Cinder only uses rtslib-fb.

**Comment by agrover** [comment]
Thanks @haypo! :+1:

**Comment by haypo** [comment]
Cool. Do you plan to release a new version including this change?

**Comment by agrover** [comment]
Sure, no prob.

**Pull request merged**
